import { ADMIN_GAME_ACTION } from "../../type";

export const ADMIN_GAME_ACTION_DATA = {
  [ADMIN_GAME_ACTION.PLAY_GAME]: {
    action: ADMIN_GAME_ACTION.PLAY_GAME,
    payload: ADMIN_GAME_ACTION.PLAY_GAME,
  },
  [ADMIN_GAME_ACTION.PAUSE_GAME]: {
    action: ADMIN_GAME_ACTION.PAUSE_GAME,
    payload: ADMIN_GAME_ACTION.PAUSE_GAME,
  },
  [ADMIN_GAME_ACTION.SKIP_QUESTION]: {
    action: ADMIN_GAME_ACTION.SKIP_QUESTION,
    payload: ADMIN_GAME_ACTION.SKIP_QUESTION,
  },
};
